version: "3"

services:
  speedtest:
    domainname: "${DOMAIN_NAME}"
    hostname: "${HOST_NAME}"
    image: adolfintel/speedtest:latest
    labels:
      traefik.domain: "${HOST_NAME}.${DOMAIN_NAME}"
      traefik.frontend.rule: "Host: speedtest.${HOST_NAME}.${DOMAIN_NAME}"
    restart: always

networks:
  default:
    external:
      name: "webhost"
