version: "3"

services:
  openspeedtest:
    environment:
      VIRTUAL_HOST: "speedtest.${HOST_NAME}"
      VIRTUAL_PORT: "80"
    image: adolfintel/speedtest:latest
    restart: always

networks:
  default:
    external:
      name: "webhost"

