version: "3"

services:
  speedtest:
    domainname: "${DOMAIN_NAME}"
    environment:
      VIRTUAL_HOST: "speedtest.${HOST_NAME}.${DOMAIN_NAME}"
      VIRTUAL_PORT: "80"
    hostname: "${HOST_NAME}"
    image: adolfintel/speedtest:latest
    restart: always

networks:
  default:
    external:
      name: "webhost"
